FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Variables de entorno para desarrollo
ENV PORT=3001
ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

# Exponer el puerto configurado
EXPOSE 3001

# Iniciar la aplicación en modo desarrollo
CMD ["npm", "start"]
